version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - travel-a2a-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - backend-data:/app/data
    networks:
      - travel-a2a-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: MCP Server (if you want to run it locally)
  # mcp-server:
  #   image: mcp-server:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - MCP_API_KEY=${MCP_API_KEY}
  #   networks:
  #     - travel-a2a-network

volumes:
  backend-data:

networks:
  travel-a2a-network:
    driver: bridge
